import Feature from '@/components/feature'
import Intro from '@/components/intro'
import ProductList from '@/components/product-list'
import Tabs from '@/components/tabs'
import { Button, TextField, Typography } from '@mui/material'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>ژاکت | مارکت وردپرس | قالب وردپرس | پوسته وردپرس</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro/>
      <Tabs/>
      <Feature/>
      <ProductList />
    </>
  )
}
